### PR TITLE
Actually build the library to include changes from #1 and #2

### PR DESCRIPTION
**Pull request by gabro**
Let's try again. Same as #3 but this time I built the correct version hopefully...

### CODE REVIEW

**Comment by jeffcarp** [comment]
Oops, my bad, I should have caught that. Your contributions are appreciated!! :stars: :+1:

**Comment by jeffcarp** [comment]
Pushed version `1.0.1` to npm including this.

**Comment by jeffcarp** [comment]
@gabro I can add you as a maintainer of this repo if you have other changes in mind, let me know :smile:

**Comment by gabro** [comment]
@jeffcarp sure, why not ^^ I'm using this component in a project I'm working on right now, so I'll probably add more functionalities as I need them.
For instance I'm currently adding a props for the `onReady` event added in the 2.7 version (see: https://github.com/braintree/braintree-web/issues/19)

**Comment by jeffcarp** [comment]
Awesome! Added! This weekend I'd like to try to set up better integration testing for this repo.

**Pull request merged**
