### PR TITLE
replace ES6  with  so don't need transpiler

### PR DESCRIPTION
**Pull request by christensena**
`const` is ES6 only so will go fine on some browsers but not others unless transpiled.

I found when trying to use my app from an iPhone.

### CODE REVIEW

**Comment by jeffcarp** [comment]
It would be helpful to find out the best practices (if any) for React components with respect to requiring transpilation, since I'd guess that the majority of people developing apps with React are already transpiling ES6 and/or JSX. Since `braintree-react` is delivered as a CommonJS module, you can't escape a build step altogether, so it's a slippery slope.

I appreciate the intent of this PR but forbidding ES6 features feels like a step backward. Is transpilation not possible in your build step? Interested to hear your thoughts on this.

**Comment by christensena** [comment]
The practice I've seen is to have the source (e.g. in `/src`) in ES6 (maybe even with ES7 or TypeScript) but when published to npm, it has been transpiled down, (though not minified! See https://github.com/braintree/braintree-web/issues/85). You can see this with the redux library https://github.com/rackt/redux for example.

My app does use ES6 and JSX and transpiles it's own code using webpack but doesn't do it for imports from `node_modules`, hence the issue I ran into. I use various libraries (e.g. Redux) that use ES6 without the issue.

My suggestion for `braintree-react` is to either put the build bits in or just stay in ES5 without JSX. Given the small amount of code, I just figured the latter was a lot easier and there's no real benefit to using JSX/ES6 yet.

**Comment by jeffcarp** [comment]
Hey @christensena sorry this late. I agree with your sentiments. As I mentioned in [a similar issue](https://github.com/jsdom/abab/issues/15#issuecomment-168063104) my plan going forward is:
1. Short term: replace `const` with `var`
2. Long term: add a Babel prepublish step so that we can use ES6 features but publish ES5 code (as you suggested)

So I'll accept this PR, push a new version, and let you know here. Thanks again for bringing this up and for submitting the PR!

**Comment by jeffcarp** [comment]
Merged as f6f87541b1eafa8d32188af9025f4bc4a9ff5a60 in [3.0.1](https://github.com/jeffcarp/braintree-react/blob/master/CHANGELOG.md#301---december-2015)!

**Pull request closed without merging**
