### PR TITLE
Braintree-web as prop

### PR DESCRIPTION
**Pull request by ascariandrea**
I changed how `braintree-web` dependency is handled in the DropIn components for two reasons:
1 - I think if it is required in the project it has to be also defined as dependency in the `package.json`.
2 - The import of the module doesn't work for isomorphic application.

So I decided to pass it as prop of DropIn component.
No more "hidden" dependency and isomorphism compatibility :+1:.

What do you think?
Thanks in advance.

### CODE REVIEW

**Comment by gabro** [comment]
I think this makes sense.

The ideal fix would be to make `braintree-web` isomorphic, but since it's not open-source that's not really an option here.

Passing the braintree-web instances as a prop solves the issue in an acceptable way. In non-isomorphic apps, it's only a matter of passing `require('braintree-web')` as a prop, which looks like a bearable burden.

That having being said, @ascariandrea can you please also fix the tests and update the readme?

@jeffcarp, thoughts?

**Comment by ascariandrea** [comment]
@gabro I fixed the tests, but I want to wait @jeffcarp before edit README.

**Comment by gabro** [comment]
:+1:

**Comment by jeffcarp** [comment]
Hey @ascariandrea, thanks for the PR! :smile: 

Let me make sure I understand you correctly. Is the intention here that you could server-side render this component and then on the front-end, load braintree-web via a script tag and pass in `braintree` to the Drop-In component?

> 1 - I think if it is required in the project it has to be also defined as dependency in the package.json

It should be enough that `braintree-web` is [already defined in dependencies](https://github.com/jeffcarp/braintree-react/blob/bf94181943f688aa2f5adc084e327db06c51d139/package.json#L35). I don't think it needs to be defined in both devDependencies and dependencies. ([source](http://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencies))

If we decide to pass `braintree` as a prop, I think it should be eliminated from the build entirely and remain a devDependency only for testing + example purposes.

On one hand, bundling braintree-web so that braintree-react comes 'batteries included' (like [braintree-angular](https://github.com/jeffcarp/braintree-angular)) is really nice. But server-side rendering is more frequently a use case in the React world than in the Angular world, from my understanding. And as @gabro pointed out, including braintree-web yourself isn't a huge pain in the butt. So I'm :+1: on this change. 

[edit] Just thought of this - another positive is that it decouples you from using the version of braintree-web included in braintree-react. (Ideally braintree-react would always have the most up-to-date version of braintree-web but historically this hasn't been the case).

Moving forward:
- Can you remove braintree-web from dependencies (and keep it in devDependencies)
- As soon as I get some free time I'll take this branch for a spin
- The README should be updated to reflect the new usage (I can do this if you don't have time)
- I'll squash everything, merge, and do a major version bump

Thanks again! :smile: :+1:

**Comment by ascariandrea** [comment]
I messed up with the dependencies, cause I was using an older version that haven't `braintree-web` specified as dependency.
Anyway I'm going to remove it from dependencies and update the README.

Thanks guys :smile:

**Comment by jeffcarp** [comment]
LGTM! Merged as aef010ada4feb67e498d9465677c6623451f395d and pushed in [2.0.0](https://github.com/jeffcarp/braintree-react/releases/tag/2.0.0). Let me know if everything works for you. Thanks again for the PR! :smile:

**Pull request closed without merging**
