### PR TITLE
Allow paypal props to be passed to the dropin component

### PR DESCRIPTION
**Pull request by rmdydo**

### CODE REVIEW

**Comment by jeffcarp** [comment]
Thank you @rmdydo, would you mind adding a test for this?

**Comment by rmdydo** [comment]
@jeffcarp As per your request, the test has been added.
Thanks

**Comment by jeffcarp** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;QdrpaDtI&#x2F;2778-https-github-com-jeffcarp-braintree-react-pull-34"> https:&#x2F;&#x2F;github.com&#x2F;jeffcarp&#x2F;braintree-react&#x2F;pull&#x2F;34</a>

**Comment by jeffcarp** [comment]
@rmdydo Thank you, I really appreciate it! Will merge and push a new version soon.

**Pull request merged**
